- name: ping moduel
  hosts: frontend
  become: yes
  tasks: 
  - name: ping
    ansible.builtin.ping:

  - name: Install nginx
    ansible.builtin.package:
     name: nginx
     state: present

  - name: Start service nginx, if not started
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes