- name: Printing
  hosts: frontend
  tasks:
  - name: Prints two lines of messages, but only if there is an environment value set
    ansible.builtin.debug:
     msg: chandu
  
  - name: Prints two lines of messages, but only if there is an environment value set
    ansible.builtin.debug:
     msg: tharun

   