- name: fuctions
  hosts: local
  connection: local
  vars:
    habbits: Cricket, Movies, Music   ##string
    places:
      India: hyderabad
      USA: Sanfrancisco
  tasks:
  - name: default fuctions
    ansible.builtin.debug:
     msg: " hello, {{name | default('chandu')}}"

### converting  string to list###
  - name: split function
    ansible.builtin.debug:
     msg: " his habbits are, {{ habbits | split(,) }}"

#### coverting dictionary to list##
  - name: dictionary to list
    ansible.builtin.debug:
     msg: "places he lived in india and usa are , {{places | dict2items }}" ##items means list