- name: using varibales from variable.yaml file
  hosts: local
  connection: local
  vars_files:
  - varfiles.yaml
  tasks:
  - name : printing details
    ansible.builtin.debug:
     msg: name {{name}}, works at {{works_at}}, as a {{position}}